name: Devops project 3

on: push
jobs:
  devops3-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Formatting test
        run: black .

      - name: Run Lint test 
        run: flake8 . 

      - name: 
        run: bandit -r . -s B201
